---

- name: Pull SonarQube Docker image
  docker_image:
    name: sonarqube
    tag: community
    source: pull

- name: Create volume for SonarQube data
  docker_volume:
    name: sonarqube_data

- name: Create network for SonarQube
  docker_network:
    name: sonarqube_network

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:community
    state: started
    restart_policy: always
    published_ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_data:/opt/sonarqube/extensions
      - sonarqube_data:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/temp
    networks:
      - sonarqube_network
    # env:
    #   SONAR_JDBC_URL: jdbc:h2:mem:sonar
