all:
  hosts:
    54.92.203.232:
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_user: admin #ubuntu#ec2-user